// svelte/src/App.svelte
<script lang="ts">
  import "../../style.css";
  import { onMount } from "svelte";

  type Todo = {
    value: string;
    completed: boolean;
  };
  let todos: Todo[] = [];
  let completedCount = 0;
  let input = "";

  const readLocalStorage = (key: string, fallback: any) => {
    if (localStorage.getItem(key)) return JSON.parse(localStorage[key]);
    else return fallback;
  };

  const writeLocalStorage = (key: string, value: any) => {
    localStorage.setItem(key, JSON.stringify(value));
  };

  onMount(() => {
    todos = readLocalStorage("todoodle--todos", []);
    completedCount = readLocalStorage("todoodle--completedCount", 0);
  });

  $: if (todos.length > 0) writeLocalStorage("todoodle--todos", todos);
  $: if (completedCount > 0)
    writeLocalStorage("todoodle--completedCount", completedCount);

  const addTodo = () => {
    if (input !== "") {
      todos = [...todos, { value: input, completed: false }];
      input = "";
    }
  };

  const toggleTodo = (index: number) => {
    todos[index].completed = !todos[index].completed;
  };

  const removeTodo = (index: number) => {
    if (todos[index].completed) completedCount++;
    todos = todos.filter((_, i) => i !== index);
  };

  const resetCount = () => {
    completedCount = 0;
    writeLocalStorage("todoodle--completedCount", 0);
  };
</script>

<main>
  <div id="app">
    <h1 class="header">Svelte</h1>

    <div class="completed-wrapper">
      <h3 class="completed-count">{completedCount} completed tasks</h3>
      <button class="completed-reset" on:click={resetCount}>Reset</button>
    </div>

    <div class="input-wrapper">
      <input
        class="input-input"
        type="text"
        placeholder="Create a new to-do"
        bind:value={input}
        on:keydown={(e) => e.key === "Enter" && addTodo()}
      />
      <button class="input-button" on:click={addTodo}>Add</button>
    </div>

    <div class="todos-wrapper">
      {#each todos as task, index}
        <div
          class="todos-container"
          class:completed={todos[index].completed}
          on:click={() => toggleTodo(index)}
        >
          <span class="todos-todo">{task.value}</span>
          <button
            class="todos-delete"
            on:click|stopPropagation={() => removeTodo(index)}
          />
        </div>
      {/each}
    </div>
  </div>
</main>

<style>
  .header {
    color: #ff8a65;
    text-shadow: 1px 1px #ff5722, 2px 2px #e64a19, 3px 3px #bf360c;
  }
</style>

// vue/src/App.vue
<script setup lang="ts">
import '../../style.css'
import { ref, onMounted } from 'vue'

type Todo = {
  value: string,
  completed: boolean
}
const todos = ref<Todo[]>([])
const completedCount = ref(0)
const input = ref("")

const readLocalStorage = (key: string, fallback: any) => {
  if (localStorage.getItem(key)) return JSON.parse(localStorage[key])
  else return fallback
}

const writeLocalStorage = (key: string, value: any) => {
  localStorage.setItem(key, JSON.stringify(value))
}

onMounted(() => {
  todos.value = readLocalStorage('todoodle--todos', [])
  completedCount.value = readLocalStorage('todoodle--completedCount', 0)
})

const addTodo = () => {
  if (input.value === "") return
  todos.value = [...todos.value, {
    value: input.value,
    completed: false
  }]
  writeLocalStorage('todoodle--todos', todos.value)
  input.value = ""
}

const removeTodo = (index: number) => {
  if (todos.value[index].completed) {
    completedCount.value++
    writeLocalStorage('todoodle--completedCount', completedCount.value)
  }
  todos.value = todos.value.filter((_, i) => i !== index)
  writeLocalStorage('todoodle--todos', todos.value)
}

const toggleTodo = (index: number) => {
  const shallowState = todos.value
  shallowState[index].completed = !shallowState[index].completed
  todos.value = shallowState
}

const resetCount = () => {
  completedCount.value = 0
  writeLocalStorage('todoodle-completedCount', completedCount.value)
}
</script>

<template>

<div id="app">

  <h1 className="header">Vue</h1>

  <div className="completed-wrapper">
    <h3 className="completed-count">
      {{ completedCount }} completed tasks
    </h3>
    <button className="completed-reset" @click="resetCount">Reset</button>
  </div>

  <div className="input-wrapper">
    <input
      className="input-input"
      type="text"
      placeholder="Create a new to-do"
      v-model="input"
      @keydown.enter="addTodo"
    />
    <button className="input-button" @click="addTodo">Add</button>
  </div>

  <div className="todos-wrapper">
    <div 
      v-for="(task, index) in todos"
      :key="index"
      class="todos-container"
      :class="{'completed': task.completed}"
      @click="toggleTodo(index)"
    >
      <span className="todos-todo">{{ task.value }}</span>
      <button className="todos-delete" @click.stop="removeTodo(index)"/>
    </div>
  </div>

</div>

</template>

<style scoped>
h1 {
  color: #66bb6a;
  text-shadow: 1px 1px #388e3c, 2px 2px #1b5e20;
}
</style>
