// vue/src/App.vue
<script setup lang="ts">
import '../../style.css'
import { ref, onMounted } from 'vue'

type Todo = {
  value: string,
  completed: boolean
}
const todos = ref<Todo[]>([])
const completedCount = ref(0)
const input = ref("")

const readLocalStorage = (key: string, fallback: any) => {
  if (localStorage.getItem(key)) return JSON.parse(localStorage[key])
  else return fallback
}

const writeLocalStorage = (key: string, value: any) => {
  localStorage.setItem(key, JSON.stringify(value))
}

onMounted(() => {
  todos.value = readLocalStorage('todoodle--todos', [])
  completedCount.value = readLocalStorage('todoodle--completedCount', 0)
})

const addTodo = () => {
  if (input.value === "") return
  todos.value = [...todos.value, {
    value: input.value,
    completed: false
  }]
  writeLocalStorage('todoodle--todos', todos.value)
  input.value = ""
}

const removeTodo = (index: number) => {
  if (todos.value[index].completed) {
    completedCount.value++
    writeLocalStorage('todoodle--completedCount', completedCount.value)
  }
  todos.value = todos.value.filter((_, i) => i !== index)
  writeLocalStorage('todoodle--todos', todos.value)
}

const toggleTodo = (index: number) => {
  const shallowState = todos.value
  shallowState[index].completed = !shallowState[index].completed
  todos.value = shallowState
}

const resetCount = () => {
  completedCount.value = 0
  writeLocalStorage('todoodle-completedCount', completedCount.value)
}
</script>

<template>

<div id="app">

  <h1 className="header">Vue</h1>

  <div className="completed-wrapper">
    <h3 className="completed-count">
      {{ completedCount }} completed tasks
    </h3>
    <button className="completed-reset" @click="resetCount">Reset</button>
  </div>

  <div className="input-wrapper">
    <input
      className="input-input"
      type="text"
      placeholder="Create a new to-do"
      v-model="input"
      @keydown.enter="addTodo"
    />
    <button className="input-button" @click="addTodo">Add</button>
  </div>

  <div className="todos-wrapper">
    <div 
      v-for="(task, index) in todos"
      :key="index"
      class="todos-container"
      :class="{'completed': task.completed}"
      @click="toggleTodo(index)"
    >
      <span className="todos-todo">{{ task.value }}</span>
      <button className="todos-delete" @click.stop="removeTodo(index)"/>
    </div>
  </div>

</div>

</template>

<style scoped>
h1 {
  color: #66bb6a;
  text-shadow: 1px 1px #388e3c, 2px 2px #1b5e20;
}
</style>

// angular/src/app/app.component.ts
import { Component, DoCheck, Input, OnChanges, OnInit, SimpleChanges } from '@angular/core'

type Todo = {
  value: string,
  completed: boolean
}

@Component({
  selector: 'app-root',
  styleUrls: ['../../../style.css'],
  template:`
    <div id='app'>

      <h1 class='header'>Angular</h1>

      <div class="completed-wrapper">
        <h3 class="completed-count">
          {{ completedCount }} completed tasks
        </h3>
        <button 
          class="completed-reset"
          (click)="completedCount = 0"
        >
          Reset
        </button>
      </div>

      <div class="input-wrapper">
        <input 
          class="input-input"
          type="text"
          name="input-thing"
          [(ngModel)]="input"
        />
        <button 
          class="input-button"
          (click)="addTodo()"
        >
          Add
        </button>
      </div>

      <div class="todos-wrapper">
        <div 
          class="todos-container"
          *ngFor="let task of todos; let index = index;"
          [class.completed]="task.completed"
          (click)="toggleTodo(index)"
        >
          <span class="todos-todo">{{ task.value }}</span>
          <button 
          class="todos-delete"
          (click)="removeTodo(index)"
          ></button>
        </div>
      </div>

    </div>
  `
})
export class AppComponent implements OnInit, DoCheck {
  title = 'angular'

  todos: Todo[] = []
  completedCount: number = 0
  input: string = ""


  readLocalStorage = (key: string, fallback: any) => {
    if (localStorage.getItem(key)) return JSON.parse(localStorage[key])
    else return fallback
  }

  writeLocalStorage = (key: string, value: any) => {
    localStorage.setItem(key, JSON.stringify(value))
  }

  ngOnInit(): void {
      this.todos = this.readLocalStorage('todoodle--todos', [])
      this.completedCount = this.readLocalStorage('todoodle--completedCount', 0)
  }

  oldTodos: Todo[] = []
  oldCompletedCount: number = 0

  ngDoCheck() {
    if (this.todos !== this.oldTodos) {
      this.writeLocalStorage('todoodle--todos', this.todos)
      this.oldTodos = this.todos
    }
    if (this.completedCount !== this.oldCompletedCount) {
      this.writeLocalStorage('todoodle--completedCount', this.completedCount)
      this.oldCompletedCount = this.completedCount
    }
  }

  handleInput = (e: { currentTarget: { value: string } }) => 
    { this.input = e.currentTarget.value }

  addTodo = () => {
    if (this.input !== "") {
      this.todos = [...this.todos, { value: this.input, completed: false }]
    }
  }

  removeTodo = (index: number) => {
    if (this.todos[index].completed) this.completedCount++
    this.todos = this.todos.filter((_, i) => i !== index)
  }

  toggleTodo = (index: number) => {
    this.todos[index].completed = !this.todos[index].completed
  }
}
