// react/src/main.tsx
import React, { useState, useEffect } from 'react'
import ReactDOM from 'react-dom/client'
import '../../style.css'

const App = () => {

  type Todo = {
    value: string,
    completed: boolean
  }
  const [ todos, setTodos ] = useState<Todo[]>([])
  const [ completedCount, setCompletedCount ] = useState(0)
  const [ input, setInput ] = useState("")

  const readLocalStorage = (key: string, fallback: any) => {
    if (localStorage.getItem(key)) return JSON.parse(localStorage[key])
    else return fallback
  }

  const writeLocalStorage = (key: string, value: any) => {
    localStorage.setItem(key, JSON.stringify(value))
  }

  useEffect(() => {
    setTodos(readLocalStorage('todoodle--todos', []))
    setCompletedCount(readLocalStorage('todoodle--completedCount', 0))
  }, [])

  useEffect(() => {
    writeLocalStorage('todoodle--todos', todos)
  }, [todos])

  useEffect(() => {
    writeLocalStorage('todoodle--completedCount', completedCount)
  }, [completedCount])

  const addTodo = () => {
    if (input === "") return
    setTodos(state => [...state, { value: input, completed: false }])
    setInput('')
  }

  const toggleTodo = (index: number) => {
    const shallowState = [...todos]
    shallowState[index].completed = !shallowState[index].completed
    setTodos(shallowState)
  }

  const removeTodo = (index: number) => {
    if (todos[index].completed) setCompletedCount(state => state + 1)
    setTodos(state => state.filter((_, i) => i !== index))
  }

  const resetCount = () => {
    setCompletedCount(0)
  }

  return (
    <div id="app">

    <h1 
      className="header"
      style={{
        color: "#64b5f6",
        textShadow: "1px 1px 1px #2196f3, 2px 2px 2px #1976d2, 3px 3px 3px #0d47a1"
      }}
    >
      React
    </h1>

    <div className="completed-wrapper">
      <h3 className="completed-count">{completedCount} completed tasks</h3>
      <button 
        className="completed-reset"
        onClick={resetCount}
      >
        Reset
      </button>
    </div>

    <div className="input-wrapper">
      <input 
        className="input-input"
        type="text"
        placeholder="Create a new to-do"
        value={input}
        onInput={e => setInput(e.currentTarget.value)}
        onKeyDown={e => e.key === "Enter" && addTodo()}
      />
      <button
        className="input-button"
        onClick={addTodo}
      >
        Add
      </button>
    </div>

    <div className="todos-wrapper">
      {todos.map((task, index) => 
        <div
          key={index}
          className={`todos-container ${task.completed && "completed"}`}
          onClick={() => toggleTodo(index)}
        >
          <span className="todos-todo">{task.value}</span>
          <button 
            className="todos-delete"
            onClick={e => {
              e.stopPropagation()
              removeTodo(index)
            }}
          />
        </div>
      )}
    </div>

    </div>
  )
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)

// solid/src/index.tsx
/* @refresh reload */
import { createSignal, createEffect, onMount, For } from 'solid-js'
import { render } from 'solid-js/web'
import '../../style.css'

const App = () => {

    type Todo = {
        value: string,
        completed: boolean
    }
    const [ todos, setTodos ] = createSignal<Todo[]>([])
    const [ completedCount, setCompletedCount ] = createSignal(0)
    const [ input, setInput ] = createSignal("")

    const readLocalStorage = (key: string, fallback: any) => {
        if (localStorage.getItem(key)) return JSON.parse(localStorage[key])
        else return fallback
    }

    const writeLocalStorage = (key: string, value: any) => {
        localStorage.setItem(key, JSON.stringify(value))
    }

    onMount(() => {
        setTodos(readLocalStorage('todoodle--todos', []))
        setCompletedCount(readLocalStorage('todoodle--completedCount', 0))
    })

    createEffect(() => {
        writeLocalStorage('todoodle--todos', todos())
        writeLocalStorage('todoodle--completedCount', completedCount())
    })

    const addTodo = () => {
        if (input() !== "") {
            setTodos(state => [...state, { value: input(), completed: false }])
            setInput("")
        }
    }

    const removeTodo = (index: number) => {
        if (todos()[index].completed) setCompletedCount(state => state + 1)
        setTodos(state => state.filter((_, i) => i !== index))
    }

    const toggleTodo = (index: number) => {
        const shallowState = [...todos()]
        shallowState[index].completed = !shallowState[index].completed
        setTodos(shallowState)
    }

    const resetCount = () => setCompletedCount(0)

    return (
        <div id="app">

            <h1 
                class="header"
                style={{
                    'color': '#7dd3fc',
                    'text-shadow': 
                        '1px 1px 1px #0ea5e9, 2px 2px 2px #0369a1, 3px 3px 3px #0c4a6e'
                }}
            >
                Solid
            </h1>

            <div class="completed-wrapper">
                <h3 class="completed-count">
                    {completedCount} completed tasks
                </h3>
                <button 
                    class="completed-reset" 
                    onClick={resetCount}
                >
                    Reset
                </button>
            </div>

            <div class="input-wrapper">
                <input
                    class="input-input"
                    type="text"
                    placeholder="Create a new to-do"
                    value={input()}
                    onInput={e => setInput(e.currentTarget.value)}
                    onKeyDown={e => e.key === 'Enter' && addTodo()}
                />
                <button
                    class="input-button"
                    onClick={addTodo}
                >
                    Add
                </button>
            </div>

            <div class="todos-wrapper">
                <For each={todos()}>{(task, index) => 
                    <div
                        class="todos-container" 
                        // classList={{ completed: task.completed }}
                        classList={{ completed: todos()[index()].completed }}
                        onClick={() => toggleTodo(index())}
                    >
                        <span class="todos-todo">{task.value}</span>
                        <button 
                            class="todos-delete" 
                            onClick={e => {
                                e.stopPropagation()
                                removeTodo(index())
                            }} 
                        />
                    </div>
                }</For>
            </div>

        </div>
    )
}

render(() => <App />, document.getElementById('root') as HTMLElement)
